name: Run StyleLint

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions-hub/stylelint@master
      env:
          PATTERN: "assets/stylesheets/*.css"
